### ISSUE TITLE
Pre-release version of a package

### ISSUE THREAD

**Issue by robfe11** [telus/create-library#40]
**Issue**
We have the following environments setup in Home Solutions:
* Test
* Staging
* Production

We typically use the `test` environment as an integration environment so that we can test changes from multiple teams.  In those cases when we want to test a component change, we do not want to publish it as a proper version, but instead do a pre-release. 

**Solution**
The `semantic-release` team has a [pre-release](https://github.com/semantic-release/semantic-release/issues/563) feature in beta right now.  We should start using it once it's out of beta.

**Comment by ruxandrafed** [comment]
Thanks for logging this, @robfe11! We'll look into this :)

Adding this here as it's relevant: https://github.com/semantic-release/semantic-release/issues/563
